from __future__ import annotations

import argparse
import csv
import json
import math
from collections.abc import Sequence
from dataclasses import dataclass, replace
from numbers import Real
from pathlib import Path

from evaluate_authentication import (
    ScoreRecord,
    build_curve,
    compute_auc,
    compute_score_distribution,
    enforce_session_separation,
    parse_bool,
    validate_record_label,
)
from output_directory import create_generation_directory, discard_generation, publish_generation


EXPECTED_TOOTH_NAMES = ("R1", "R2", "R3", "L1", "L2", "L3")
REQUIRED_SCORE_COLUMNS = (
    "query_subject_id",
    "template_subject_id",
    "query_session_id",
    "template_session_id",
    "is_genuine",
    "per_tooth_scores",
)
METRICS_COLUMNS = (
    "tooth",
    "roc_auc",
    "d_prime",
    "genuine_mean",
    "impostor_mean",
    "genuine_count",
    "impostor_count",
)


@dataclass(frozen=True)
class PerToothScoreRecord:
    authentication: ScoreRecord
    per_tooth_scores: dict[str, float]


class DuplicateJsonKeyError(ValueError):
    pass


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate genuine/impostor discrimination for each front-tooth type."
    )
    parser.add_argument(
        "--scores-csv",
        type=Path,
        required=True,
        help="scores.csv generated by score_code_pairs.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory for per_tooth_metrics.csv and summary.json.",
    )
    return parser.parse_args(argv)


def clean_required(value: str | None, column: str, row_number: int) -> str:
    if value is None:
        raise RuntimeError(f"{column} is missing at CSV row {row_number}.")
    cleaned = value.strip()
    if cleaned == "":
        raise RuntimeError(f"{column} is empty at CSV row {row_number}.")
    return cleaned


def validate_header(fieldnames: list[str] | None, path: Path) -> None:
    if fieldnames is None:
        raise RuntimeError(f"score CSV has no header: {path}")
    if len(fieldnames) != len(set(fieldnames)):
        raise RuntimeError(f"score CSV has duplicate columns: {path}")
    missing = [column for column in REQUIRED_SCORE_COLUMNS if column not in fieldnames]
    if missing:
        raise RuntimeError(f"score CSV is missing required columns {missing}: {path}")


def reject_duplicate_json_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
    decoded: dict[str, object] = {}
    for key, value in pairs:
        if key in decoded:
            raise DuplicateJsonKeyError(f"duplicate tooth key {key!r}")
        decoded[key] = value
    return decoded


def parse_per_tooth_scores(value: str, row_number: int) -> dict[str, float]:
    try:
        decoded = json.loads(value, object_pairs_hook=reject_duplicate_json_keys)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"per_tooth_scores is invalid JSON at CSV row {row_number}."
        ) from exc
    except DuplicateJsonKeyError as exc:
        raise RuntimeError(
            f"per_tooth_scores has a duplicate tooth at CSV row {row_number}: {exc}"
        ) from exc

    if not isinstance(decoded, dict):
        raise RuntimeError(
            f"per_tooth_scores must be a JSON object at CSV row {row_number}."
        )
    if not decoded:
        raise RuntimeError(
            f"per_tooth_scores must be non-empty at CSV row {row_number}."
        )

    unknown_teeth = sorted(set(decoded) - set(EXPECTED_TOOTH_NAMES))
    if unknown_teeth:
        raise RuntimeError(
            f"per_tooth_scores has an unknown tooth at CSV row {row_number}: {unknown_teeth}"
        )

    scores: dict[str, float] = {}
    for tooth in EXPECTED_TOOTH_NAMES:
        if tooth not in decoded:
            continue
        raw_score = decoded[tooth]
        if isinstance(raw_score, bool) or not isinstance(raw_score, Real):
            raise RuntimeError(
                f"per_tooth_scores[{tooth!r}] must be a real number at CSV row {row_number}."
            )
        score = float(raw_score)
        if not math.isfinite(score):
            raise RuntimeError(
                f"per_tooth_scores[{tooth!r}] must be finite at CSV row {row_number}."
            )
        if not 0.0 <= score <= 1.0:
            raise RuntimeError(
                f"per_tooth_scores[{tooth!r}] must be from 0 to 1 at CSV row {row_number}: {score}"
            )
        scores[tooth] = score
    return scores


def parse_score_row(row: dict[str | None, str | None], row_number: int) -> PerToothScoreRecord:
    if None in row:
        raise RuntimeError(f"score CSV has extra fields at CSV row {row_number}.")
    values = {
        column: clean_required(row[column], column, row_number)
        for column in REQUIRED_SCORE_COLUMNS
    }
    authentication = ScoreRecord(
        query_id=f"csv-row-{row_number}",
        template_id=f"csv-row-{row_number}",
        query_subject_id=values["query_subject_id"],
        template_subject_id=values["template_subject_id"],
        query_session_id=values["query_session_id"],
        template_session_id=values["template_session_id"],
        is_genuine=parse_bool(values["is_genuine"], row_number),
        fused_score=0.0,
        source_row_number=row_number,
    )
    validate_record_label(authentication)
    return PerToothScoreRecord(
        authentication=authentication,
        per_tooth_scores=parse_per_tooth_scores(values["per_tooth_scores"], row_number),
    )


def load_score_records(path: Path) -> list[PerToothScoreRecord]:
    try:
        handle = path.open(newline="", encoding="utf-8-sig")
    except OSError as exc:
        raise RuntimeError(f"failed to open score CSV: {path}") from exc

    with handle:
        reader = csv.DictReader(handle)
        validate_header(reader.fieldnames, path)
        records = [
            parse_score_row(row, row_number)
            for row_number, row in enumerate(reader, start=2)
        ]
    if not records:
        raise RuntimeError(f"score CSV has no records: {path}")
    return records


def filter_same_session_genuine(
    records: list[PerToothScoreRecord],
) -> tuple[list[PerToothScoreRecord], int]:
    authentication_records = [record.authentication for record in records]
    kept_authentication, excluded = enforce_session_separation(authentication_records)
    kept_rows = {record.source_row_number for record in kept_authentication}
    kept = [
        record
        for record in records
        if record.authentication.source_row_number in kept_rows
    ]
    return kept, excluded


def class_counts(records: list[ScoreRecord]) -> tuple[int, int]:
    genuine_count = sum(record.is_genuine for record in records)
    return genuine_count, len(records) - genuine_count


def unevaluated_result(
    reason: str,
    genuine_count: int,
    impostor_count: int,
    used_records: int,
) -> dict[str, object]:
    return {
        "status": "not_evaluated",
        "reason": reason,
        "genuine_count": genuine_count,
        "impostor_count": impostor_count,
        "missing_score_records": used_records - genuine_count - impostor_count,
    }


def evaluate_per_tooth(
    records: list[PerToothScoreRecord],
) -> dict[str, dict[str, object]]:
    results: dict[str, dict[str, object]] = {}
    for tooth in EXPECTED_TOOTH_NAMES:
        tooth_records = [
            replace(record.authentication, fused_score=record.per_tooth_scores[tooth])
            for record in records
            if tooth in record.per_tooth_scores
        ]
        genuine_count, impostor_count = class_counts(tooth_records)
        if not tooth_records:
            results[tooth] = unevaluated_result(
                "no_scores", genuine_count, impostor_count, len(records)
            )
            continue
        if genuine_count == 0:
            results[tooth] = unevaluated_result(
                "missing_genuine_class", genuine_count, impostor_count, len(records)
            )
            continue
        if impostor_count == 0:
            results[tooth] = unevaluated_result(
                "missing_impostor_class", genuine_count, impostor_count, len(records)
            )
            continue

        points = build_curve(tooth_records)
        distribution = compute_score_distribution(tooth_records)
        results[tooth] = {
            "status": "evaluated",
            "genuine_count": genuine_count,
            "impostor_count": impostor_count,
            "missing_score_records": len(records) - len(tooth_records),
            "roc_auc": compute_auc(points),
            "d_prime": distribution.d_prime,
            "genuine_mean": distribution.genuine_mean,
            "impostor_mean": distribution.impostor_mean,
        }
    return results


def write_metrics_csv(path: Path, per_tooth: dict[str, dict[str, object]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=METRICS_COLUMNS)
        writer.writeheader()
        for tooth in EXPECTED_TOOTH_NAMES:
            result = per_tooth[tooth]
            if result["status"] != "evaluated":
                continue
            d_prime = result["d_prime"]
            writer.writerow(
                {
                    "tooth": tooth,
                    "roc_auc": f"{result['roc_auc']:.12g}",
                    "d_prime": "" if d_prime is None else f"{d_prime:.12g}",
                    "genuine_mean": f"{result['genuine_mean']:.12g}",
                    "impostor_mean": f"{result['impostor_mean']:.12g}",
                    "genuine_count": result["genuine_count"],
                    "impostor_count": result["impostor_count"],
                }
            )


def write_outputs_atomic(output_dir: Path, summary: dict[str, object]) -> None:
    generation_dir = create_generation_directory(output_dir)
    try:
        per_tooth = summary["per_tooth"]
        if not isinstance(per_tooth, dict):
            raise RuntimeError("summary per_tooth must be a dictionary.")
        write_metrics_csv(generation_dir / "per_tooth_metrics.csv", per_tooth)
        (generation_dir / "summary.json").write_text(
            json.dumps(summary, indent=2, ensure_ascii=False, allow_nan=False) + "\n",
            encoding="utf-8",
        )
        publish_generation(generation_dir, output_dir)
    finally:
        discard_generation(generation_dir)


def run(args: argparse.Namespace) -> dict[str, object]:
    raw_records = load_score_records(args.scores_csv)
    records, excluded_same_session_genuine = filter_same_session_genuine(raw_records)
    per_tooth = evaluate_per_tooth(records)
    summary: dict[str, object] = {
        "scores_csv_name": args.scores_csv.name,
        "total_records": len(raw_records),
        "used_records": len(records),
        "excluded_same_session_genuine": excluded_same_session_genuine,
        "evaluated_teeth": sum(
            result["status"] == "evaluated" for result in per_tooth.values()
        ),
        "per_tooth": per_tooth,
    }
    write_outputs_atomic(args.output_dir, summary)
    return summary


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    summary = run(args)
    print(f"metrics: {args.output_dir / 'per_tooth_metrics.csv'}")
    print(f"summary: {args.output_dir / 'summary.json'}")
    print(
        f"used_records={summary['used_records']} "
        f"excluded_same_session_genuine={summary['excluded_same_session_genuine']} "
        f"evaluated_teeth={summary['evaluated_teeth']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
