from __future__ import annotations

import argparse
import atexit
import csv
import json
import math
import os
import shutil
import tempfile
from collections import defaultdict
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
import torch
from PIL import Image, ImageDraw
from torch import nn
from torchvision.models import ResNet50_Weights, resnet50

from code_photos import normalize_sha256, parse_photographs, resolve_photo_reference, sha256_file
from matching_core import (
    TOOTH_NAMES,
    aggregate_embeddings,
    masked_square_crop,
    normalize_embedding,
    normalize_tooth_axis,
)
from output_directory import create_generation_directory, discard_generation, publish_generation


_ULTRALYTICS_CONFIG_DIR: Path | None = None
if "YOLO_CONFIG_DIR" not in os.environ:
    _ULTRALYTICS_CONFIG_DIR = Path(tempfile.mkdtemp(prefix="odonto_auth_ultralytics_"))
    os.environ["YOLO_CONFIG_DIR"] = str(_ULTRALYTICS_CONFIG_DIR)
    atexit.register(shutil.rmtree, _ULTRALYTICS_CONFIG_DIR)

from ultralytics import YOLO


PAIR_COLUMNS = (
    "split",
    "pair_id",
    "template_id",
    "query_id",
    "template_patient_id",
    "query_patient_id",
    "template_checkup_id",
    "query_checkup_id",
    "template_photographs",
    "query_photographs",
)
MODEL_CLASS_TO_TOOTH_INDEX = {0: 0, 1: 1, 2: 2, 7: 3, 8: 4, 9: 5}
FEATURE_NAMES = ("resnet50", "hog")
PREPROCESSING_FORMAT_VERSION = "tooth-axis-normalized-crop-v1"
RESNET_WEIGHTS_NAME = "IMAGENET1K_V2"
RESNET_WEIGHTS_FILE = "resnet50-11ad3fa6.pth"
RESNET_WEIGHTS_URL = ResNet50_Weights.IMAGENET1K_V2.url
RESNET_WEIGHTS_SHA256 = "11ad3fa62ca79e40addfd354a8ec4b7c75143b3038b8d2a807fbc68deab379ca"


@dataclass(frozen=True)
class Checkup:
    split: str
    uid: str
    patient_id: str
    checkup_id: str
    photographs: tuple[str, ...]


@dataclass(frozen=True)
class Photo:
    checkup_uid: str
    path: Path
    reference: str
    content_sha256: str


@dataclass(frozen=True)
class CropRecord:
    checkup_uid: str
    tooth_index: int
    confidence: float
    photo_reference: str
    image: np.ndarray


@dataclass
class CheckupQuality:
    photographs_total: int = 0
    photographs_processed: int = 0
    detections: int = 0
    confidence_sum: float = 0.0


def find_project_root(start: Path) -> Path:
    for path in (start, *start.parents):
        if (path / "pyproject.toml").exists():
            return path
    raise RuntimeError(f"project root not found from: {start}")


def parse_args() -> argparse.Namespace:
    repo_root = find_project_root(Path(__file__).resolve())
    parser = argparse.ArgumentParser(
        description="Extract per-tooth COde features with the v7 segmentation model."
    )
    parser.add_argument("--pairs-csv", type=Path, required=True, help="Pair manifest generated by build_code_pair_manifest.py.")
    parser.add_argument(
        "--images-root",
        type=Path,
        required=True,
        help="Extracted COde root containing Images/Photographs.",
    )
    parser.add_argument(
        "--weights",
        type=Path,
        default=repo_root / "01_stage1_real_image_extraction" / "experiments" / "v7_best" / "weights" / "best.pt",
        help="YOLO segmentation checkpoint.",
    )
    parser.add_argument(
        "--expected-weights-sha256",
        required=True,
        help="Required SHA-256 for the checkpoint, verified before deserialization.",
    )
    parser.add_argument(
        "--resnet-weights",
        type=Path,
        default=Path(torch.hub.get_dir()) / "checkpoints" / RESNET_WEIGHTS_FILE,
        help="ResNet50 IMAGENET1K_V2 checkpoint; downloaded from PyTorch when absent.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=repo_root / "02_stage2_capture_matching" / "logs" / "code_features",
        help="Directory for features_*.npz, quality.csv, and summary.json.",
    )
    parser.add_argument("--split", default="test", help="Pair split to extract.")
    parser.add_argument("--max-pairs", type=int, default=0, help="Maximum selected rows after split filtering; 0 uses all rows.")
    parser.add_argument(
        "--feature-types",
        nargs="+",
        choices=FEATURE_NAMES,
        default=list(FEATURE_NAMES),
        help="Feature extractors to run from each segmented crop.",
    )
    parser.add_argument("--device", default="0", help="Ultralytics device, for example 0 or cpu.")
    parser.add_argument("--imgsz", type=int, default=832, help="YOLO inference image size.")
    parser.add_argument("--conf", type=float, default=0.10, help="YOLO confidence threshold.")
    parser.add_argument("--iou", type=float, default=0.70, help="YOLO NMS IoU threshold.")
    parser.add_argument(
        "--source-chunk-size",
        type=int,
        default=64,
        help="Number of paths loaded into one in-memory Ultralytics batch.",
    )
    parser.add_argument("--feature-batch-size", type=int, default=16, help="Maximum crop batch size for ResNet50.")
    parser.add_argument("--crop-size", type=int, default=224, help="Square crop output size.")
    parser.add_argument("--crop-padding", type=float, default=0.12, help="Fractional padding around each tooth mask.")
    parser.add_argument(
        "--max-views-per-tooth",
        type=int,
        default=3,
        help="Highest-confidence views aggregated for each tooth and checkup.",
    )
    parser.add_argument(
        "--audit-crops",
        type=int,
        default=0,
        help="Save this many highest-confidence masked crops and a contact sheet; 0 disables it.",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Validate pair rows, weights, and image references without loading models.",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.max_pairs < 0:
        raise RuntimeError("--max-pairs must be non-negative.")
    if args.imgsz <= 0:
        raise RuntimeError("--imgsz must be positive.")
    if not 0.0 < args.conf <= 1.0:
        raise RuntimeError("--conf must be in (0, 1].")
    if not 0.0 < args.iou <= 1.0:
        raise RuntimeError("--iou must be in (0, 1].")
    if args.source_chunk_size <= 0:
        raise RuntimeError("--source-chunk-size must be positive.")
    if args.feature_batch_size <= 0:
        raise RuntimeError("--feature-batch-size must be positive.")
    if args.crop_size <= 0:
        raise RuntimeError("--crop-size must be positive.")
    if not math.isfinite(args.crop_padding) or args.crop_padding < 0.0:
        raise RuntimeError("--crop-padding must be finite and non-negative.")
    if args.max_views_per_tooth <= 0:
        raise RuntimeError("--max-views-per-tooth must be positive.")
    if args.audit_crops < 0:
        raise RuntimeError("--audit-crops must be non-negative.")
    if len(set(args.feature_types)) != len(args.feature_types):
        raise RuntimeError("--feature-types must not contain duplicates.")


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise RuntimeError(f"{label} was not found: {path}")


def clean_required(value: str, column: str, row_number: int) -> str:
    cleaned = value.strip()
    if cleaned == "":
        raise RuntimeError(f"{column} is empty at CSV row {row_number}.")
    return cleaned


def validate_pair_header(fieldnames: list[str] | None, path: Path) -> None:
    if fieldnames is None:
        raise RuntimeError(f"pair CSV has no header: {path}")
    missing = [column for column in PAIR_COLUMNS if column not in fieldnames]
    if missing:
        raise RuntimeError(f"pair CSV is missing required columns {missing}: {path}")


def add_checkup(
    checkups: dict[str, Checkup],
    *,
    split: str,
    uid: str,
    patient_id: str,
    checkup_id: str,
    photographs: tuple[str, ...],
    row_number: int,
) -> None:
    expected_uid = f"{patient_id}:{checkup_id}"
    if uid != expected_uid:
        raise RuntimeError(
            f"checkup UID mismatch at CSV row {row_number}: expected={expected_uid!r}, actual={uid!r}"
        )
    checkup = Checkup(
        split=split,
        uid=uid,
        patient_id=patient_id,
        checkup_id=checkup_id,
        photographs=photographs,
    )
    if uid in checkups and checkups[uid] != checkup:
        raise RuntimeError(f"inconsistent metadata for checkup {uid!r} at CSV row {row_number}.")
    checkups[uid] = checkup


def load_selected_checkups(path: Path, split: str, max_pairs: int) -> tuple[dict[str, Checkup], list[str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        validate_pair_header(reader.fieldnames, path)
        checkups: dict[str, Checkup] = {}
        pair_ids: list[str] = []
        for row_number, row in enumerate(reader, start=2):
            row_split = clean_required(row["split"], "split", row_number)
            if row_split != split:
                continue
            if max_pairs and len(pair_ids) >= max_pairs:
                break

            pair_id = clean_required(row["pair_id"], "pair_id", row_number)
            pair_ids.append(pair_id)
            for prefix in ("template", "query"):
                add_checkup(
                    checkups,
                    split=row_split,
                    uid=clean_required(row[f"{prefix}_id"], f"{prefix}_id", row_number),
                    patient_id=clean_required(
                        row[f"{prefix}_patient_id"], f"{prefix}_patient_id", row_number
                    ),
                    checkup_id=clean_required(
                        row[f"{prefix}_checkup_id"], f"{prefix}_checkup_id", row_number
                    ),
                    photographs=parse_photographs(
                        row[f"{prefix}_photographs"], f"{prefix}_photographs", row_number
                    ),
                    row_number=row_number,
                )

    if not pair_ids:
        raise RuntimeError(f"no pair rows found for split {split!r}: {path}")
    return checkups, pair_ids


def resolve_photos(checkups: dict[str, Checkup], images_root: Path) -> list[Photo]:
    if not images_root.is_dir():
        raise RuntimeError(f"COde images root was not found: {images_root}")

    photos: list[Photo] = []
    hash_by_path: dict[Path, str] = {}
    for checkup in sorted(checkups.values(), key=lambda item: item.uid):
        for reference in checkup.photographs:
            path = resolve_photo_reference(images_root, reference)
            if path not in hash_by_path:
                hash_by_path[path] = sha256_file(path)
            photos.append(
                Photo(
                    checkup_uid=checkup.uid,
                    path=path,
                    reference=reference,
                    content_sha256=hash_by_path[path],
                )
            )
    return photos


def torch_device(device: str) -> torch.device:
    if device == "cpu":
        return torch.device("cpu")
    if device.isdigit():
        if not torch.cuda.is_available():
            raise RuntimeError(f"CUDA device {device} was requested but torch.cuda.is_available() is false.")
        return torch.device(f"cuda:{device}")
    parsed = torch.device(device)
    if parsed.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError(f"CUDA device {device!r} was requested but CUDA is unavailable.")
    return parsed


def prepare_resnet_checkpoint(path: Path) -> str:
    if path.is_symlink():
        raise RuntimeError(f"ResNet50 checkpoint must not be a symlink: {path}")
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        torch.hub.download_url_to_file(
            RESNET_WEIGHTS_URL,
            str(path),
            hash_prefix=RESNET_WEIGHTS_SHA256,
            progress=True,
        )
    if not path.is_file():
        raise RuntimeError(f"ResNet50 checkpoint was not found: {path}")
    actual_sha256 = sha256_file(path)
    if actual_sha256 != RESNET_WEIGHTS_SHA256:
        raise RuntimeError(
            "ResNet50 weight SHA-256 mismatch: "
            f"expected={RESNET_WEIGHTS_SHA256}, actual={actual_sha256}"
        )
    return actual_sha256


def load_verified_resnet_state_dict(path: Path) -> dict[str, torch.Tensor]:
    prepare_resnet_checkpoint(path)
    state_dict = torch.load(path, map_location="cpu", weights_only=True)
    if not isinstance(state_dict, dict):
        raise RuntimeError(f"ResNet50 checkpoint must contain a state dict: {path}")
    return state_dict


def build_resnet(device: torch.device, checkpoint_path: Path) -> tuple[nn.Module, object]:
    weights = ResNet50_Weights.IMAGENET1K_V2
    model = resnet50(weights=None)
    model.load_state_dict(load_verified_resnet_state_dict(checkpoint_path))
    model.fc = nn.Identity()
    model.eval()
    model.to(device)
    return model, weights.transforms()


def build_hog() -> cv2.HOGDescriptor:
    return cv2.HOGDescriptor(
        _winSize=(128, 128),
        _blockSize=(32, 32),
        _blockStride=(16, 16),
        _cellSize=(16, 16),
        _nbins=9,
    )


def extract_resnet_batch(
    records: list[CropRecord],
    model: nn.Module,
    transform: object,
    device: torch.device,
) -> list[np.ndarray]:
    tensors = [transform(Image.fromarray(record.image)) for record in records]
    batch = torch.stack(tensors).to(device)
    with torch.inference_mode():
        output = model(batch).detach().cpu().numpy()
    if output.ndim != 2 or output.shape[0] != len(records):
        raise RuntimeError(f"unexpected ResNet50 output shape: {output.shape}")
    return [normalize_embedding(vector) for vector in output]


def extract_hog_batch(records: list[CropRecord], hog: cv2.HOGDescriptor) -> list[np.ndarray]:
    features: list[np.ndarray] = []
    for record in records:
        gray = cv2.cvtColor(record.image, cv2.COLOR_RGB2GRAY)
        resized = cv2.resize(gray, (128, 128), interpolation=cv2.INTER_AREA)
        descriptor = hog.compute(resized)
        if descriptor is None:
            raise RuntimeError(f"HOG extraction failed for {record.photo_reference}")
        features.append(normalize_embedding(descriptor.reshape(-1)))
    return features


def retain_feature_view(
    views: list[tuple[np.ndarray, float, str]],
    feature: np.ndarray,
    confidence: float,
    photo_reference: str,
    limit: int,
) -> None:
    if limit <= 0:
        raise RuntimeError("feature view limit must be positive.")
    views.append(
        (
            np.asarray(feature, dtype=np.float32),
            float(confidence),
            photo_reference,
        )
    )
    views.sort(key=lambda item: (-item[1], item[2]))
    del views[limit:]


def flush_crop_buffer(
    records: list[CropRecord],
    feature_views: dict[str, dict[str, dict[int, list[tuple[np.ndarray, float, str]]]]],
    *,
    resnet_model: nn.Module | None,
    resnet_transform: object | None,
    hog: cv2.HOGDescriptor | None,
    device: torch.device,
    max_views_per_tooth: int,
) -> None:
    if not records:
        return

    if resnet_model is not None:
        if resnet_transform is None:
            raise RuntimeError("ResNet50 transform was not initialized.")
        resnet_features = extract_resnet_batch(records, resnet_model, resnet_transform, device)
        for record, feature in zip(records, resnet_features, strict=True):
            retain_feature_view(
                feature_views["resnet50"][record.checkup_uid][record.tooth_index],
                feature,
                record.confidence,
                record.photo_reference,
                max_views_per_tooth,
            )

    if hog is not None:
        hog_features = extract_hog_batch(records, hog)
        for record, feature in zip(records, hog_features, strict=True):
            retain_feature_view(
                feature_views["hog"][record.checkup_uid][record.tooth_index],
                feature,
                record.confidence,
                record.photo_reference,
                max_views_per_tooth,
            )
    records.clear()


def resize_mask(mask: np.ndarray, image_shape: tuple[int, int]) -> np.ndarray:
    height, width = image_shape
    if mask.shape == (height, width):
        return mask > 0.5
    resized = cv2.resize(mask.astype(np.float32), (width, height), interpolation=cv2.INTER_NEAREST)
    return resized > 0.5


def build_normalized_crop(
    image: np.ndarray,
    mask: np.ndarray,
    output_size: int,
    padding_ratio: float,
) -> np.ndarray:
    normalized_image, normalized_mask = normalize_tooth_axis(image, mask)
    return masked_square_crop(
        normalized_image,
        normalized_mask,
        output_size=output_size,
        padding_ratio=padding_ratio,
    )


def iter_photo_chunks(photos: list[Photo], chunk_size: int) -> Iterator[list[Photo]]:
    if chunk_size <= 0:
        raise RuntimeError("chunk_size must be positive.")
    for start in range(0, len(photos), chunk_size):
        yield photos[start : start + chunk_size]


def release_yolo_predictor_state(model: YOLO) -> None:
    predictor = model.predictor
    if predictor is None:
        raise RuntimeError("Ultralytics predictor was not initialized.")
    predictor.results = None
    predictor.batch = None
    predictor.dataset = None


def process_crop_chunk(
    model: YOLO,
    records: list[CropRecord],
    feature_views: dict[str, dict[str, dict[int, list[tuple[np.ndarray, float, str]]]]],
    *,
    feature_batch_size: int,
    max_views_per_tooth: int,
    resnet_model: nn.Module | None,
    resnet_transform: object | None,
    hog: cv2.HOGDescriptor | None,
    device: torch.device,
) -> None:
    release_yolo_predictor_state(model)
    for crop_batch in iter_photo_chunks(records, feature_batch_size):
        flush_crop_buffer(
            crop_batch,
            feature_views,
            resnet_model=resnet_model,
            resnet_transform=resnet_transform,
            hog=hog,
            device=device,
            max_views_per_tooth=max_views_per_tooth,
        )
    records.clear()


def retain_audit_crop(records: list[CropRecord], record: CropRecord, limit: int) -> None:
    if limit == 0:
        return
    records.append(record)
    records.sort(
        key=lambda item: (
            -item.confidence,
            item.checkup_uid,
            item.tooth_index,
            item.photo_reference,
        )
    )
    if len(records) > limit:
        records.pop()


def collect_features(
    args: argparse.Namespace,
    photos: list[Photo],
    quality: dict[str, CheckupQuality],
) -> tuple[
    dict[str, dict[str, dict[int, list[tuple[np.ndarray, float, str]]]]],
    list[CropRecord],
]:
    device = torch_device(args.device)
    selected_features = set(args.feature_types)
    resnet_model: nn.Module | None = None
    resnet_transform: object | None = None
    if "resnet50" in selected_features:
        resnet_model, resnet_transform = build_resnet(device, args.resnet_weights)
    hog = build_hog() if "hog" in selected_features else None

    model = YOLO(str(args.weights))
    model_names = model.names
    expected_names = {class_id: TOOTH_NAMES[index] for class_id, index in MODEL_CLASS_TO_TOOTH_INDEX.items()}
    actual_names = {class_id: model_names[class_id] for class_id in MODEL_CLASS_TO_TOOTH_INDEX}
    if actual_names != expected_names:
        raise RuntimeError(f"unexpected v7 class names: expected={expected_names}, actual={actual_names}")

    feature_views: dict[str, dict[str, dict[int, list[tuple[np.ndarray, float, str]]]]] = {
        feature_name: defaultdict(lambda: defaultdict(list)) for feature_name in args.feature_types
    }
    audit_crops: list[CropRecord] = []
    processed = 0
    for photo_chunk in iter_photo_chunks(photos, args.source_chunk_size):
        chunk_crops: list[CropRecord] = []
        results = model.predict(
            source=[str(photo.path) for photo in photo_chunk],
            imgsz=args.imgsz,
            conf=args.conf,
            iou=args.iou,
            device=args.device,
            retina_masks=True,
            verbose=False,
            stream=True,
        )
        try:
            for photo, result in zip(photo_chunk, results, strict=True):
                processed += 1
                quality_row = quality[photo.checkup_uid]
                quality_row.photographs_processed += 1
                image_bgr = result.orig_img
                if image_bgr is None or image_bgr.ndim != 3 or image_bgr.shape[2] != 3:
                    raise RuntimeError(f"Ultralytics returned an invalid image for {photo.path}")
                image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

                if result.boxes is None or len(result.boxes) == 0:
                    if result.masks is not None and len(result.masks.data) != 0:
                        raise RuntimeError(f"masks were returned without boxes for {photo.path}")
                    continue
                if result.masks is None:
                    raise RuntimeError(f"segmentation boxes were returned without masks for {photo.path}")

                classes = result.boxes.cls.detach().cpu().numpy().astype(int)
                confidences = result.boxes.conf.detach().cpu().numpy().astype(float)
                masks = result.masks.data.detach().cpu().numpy()
                if not (len(classes) == len(confidences) == len(masks)):
                    raise RuntimeError(f"inconsistent prediction lengths for {photo.path}")

                best_by_tooth: dict[int, tuple[float, np.ndarray]] = {}
                for class_id, confidence, mask in zip(classes, confidences, masks, strict=True):
                    normalized_class_id = int(class_id)
                    if normalized_class_id not in MODEL_CLASS_TO_TOOTH_INDEX:
                        continue
                    tooth_index = MODEL_CLASS_TO_TOOTH_INDEX[normalized_class_id]
                    if tooth_index not in best_by_tooth or confidence > best_by_tooth[tooth_index][0]:
                        best_by_tooth[tooth_index] = (
                            float(confidence),
                            resize_mask(mask, image_rgb.shape[:2]),
                        )

                for tooth_index, (confidence, mask) in best_by_tooth.items():
                    crop = build_normalized_crop(
                        image_rgb,
                        mask,
                        args.crop_size,
                        args.crop_padding,
                    )
                    crop_record = CropRecord(
                        checkup_uid=photo.checkup_uid,
                        tooth_index=tooth_index,
                        confidence=confidence,
                        photo_reference=photo.reference,
                        image=crop,
                    )
                    chunk_crops.append(crop_record)
                    retain_audit_crop(audit_crops, crop_record, args.audit_crops)
                    quality_row.detections += 1
                    quality_row.confidence_sum += confidence
        finally:
            results.close()

        del result
        del results
        process_crop_chunk(
            model,
            chunk_crops,
            feature_views,
            feature_batch_size=args.feature_batch_size,
            max_views_per_tooth=args.max_views_per_tooth,
            resnet_model=resnet_model,
            resnet_transform=resnet_transform,
            hog=hog,
            device=device,
        )
        print(f"processed_photographs={processed}/{len(photos)}", flush=True)
    if processed != len(photos):
        raise RuntimeError(f"Ultralytics result count mismatch: expected={len(photos)}, actual={processed}")
    return feature_views, audit_crops


def atomic_save_npz(path: Path, **arrays: np.ndarray) -> None:
    with tempfile.NamedTemporaryFile(dir=path.parent, suffix=".npz", delete=False) as handle:
        temporary = Path(handle.name)
    try:
        np.savez_compressed(temporary, **arrays)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def validate_feature_file_contract(
    feature_name: str,
    segmentation_weights_sha256: str,
    imgsz: int,
    conf: float,
    iou: float,
    crop_size: int,
    crop_padding: float,
    preprocessing_format_version: str,
) -> str:
    if not isinstance(feature_name, str) or feature_name.strip() != feature_name or not feature_name:
        raise RuntimeError("feature_name must be a non-empty string without surrounding whitespace.")
    normalized_weights_sha256 = normalize_sha256(
        segmentation_weights_sha256,
        "segmentation_weights_sha256",
    )
    if isinstance(imgsz, bool) or not isinstance(imgsz, (int, np.integer)) or imgsz <= 0:
        raise RuntimeError("imgsz must be a positive integer.")
    if not isinstance(conf, (float, np.floating)) or not math.isfinite(float(conf)):
        raise RuntimeError("conf must be a finite floating-point value.")
    if not 0.0 < float(conf) <= 1.0:
        raise RuntimeError("conf must be in (0, 1].")
    if not isinstance(iou, (float, np.floating)) or not math.isfinite(float(iou)):
        raise RuntimeError("iou must be a finite floating-point value.")
    if not 0.0 < float(iou) <= 1.0:
        raise RuntimeError("iou must be in (0, 1].")
    if (
        isinstance(crop_size, bool)
        or not isinstance(crop_size, (int, np.integer))
        or crop_size <= 0
    ):
        raise RuntimeError("crop_size must be a positive integer.")
    if (
        not isinstance(crop_padding, (float, np.floating))
        or not math.isfinite(float(crop_padding))
        or crop_padding < 0.0
    ):
        raise RuntimeError("crop_padding must be a finite non-negative floating-point value.")
    if preprocessing_format_version != PREPROCESSING_FORMAT_VERSION:
        raise RuntimeError(
            "unsupported preprocessing_format_version: "
            f"expected={PREPROCESSING_FORMAT_VERSION!r}, "
            f"actual={preprocessing_format_version!r}"
        )
    return normalized_weights_sha256


def write_feature_file(
    path: Path,
    feature_name: str,
    checkups: dict[str, Checkup],
    photos: list[Photo],
    views: dict[str, dict[int, list[tuple[np.ndarray, float, str]]]],
    max_views_per_tooth: int,
    *,
    segmentation_weights_sha256: str,
    imgsz: int,
    conf: float,
    iou: float,
    crop_size: int,
    crop_padding: float,
    preprocessing_format_version: str,
) -> dict[str, object]:
    normalized_weights_sha256 = validate_feature_file_contract(
        feature_name,
        segmentation_weights_sha256,
        imgsz,
        conf,
        iou,
        crop_size,
        crop_padding,
        preprocessing_format_version,
    )
    checkup_ids = sorted(checkups)
    feature_dimension = 0
    for checkup_views in views.values():
        for tooth_views in checkup_views.values():
            if tooth_views:
                feature_dimension = int(tooth_views[0][0].size)
                break
        if feature_dimension:
            break
    if feature_dimension == 0:
        raise RuntimeError(f"{feature_name} produced no tooth features.")

    embeddings = np.zeros((len(checkup_ids), len(TOOTH_NAMES), feature_dimension), dtype=np.float32)
    present = np.zeros((len(checkup_ids), len(TOOTH_NAMES)), dtype=bool)
    view_counts = np.zeros((len(checkup_ids), len(TOOTH_NAMES)), dtype=np.int32)
    mean_confidences = np.zeros((len(checkup_ids), len(TOOTH_NAMES)), dtype=np.float32)

    for checkup_index, checkup_uid in enumerate(checkup_ids):
        for tooth_index in range(len(TOOTH_NAMES)):
            if checkup_uid not in views or tooth_index not in views[checkup_uid]:
                continue
            tooth_views = views[checkup_uid][tooth_index]
            selected = sorted(tooth_views, key=lambda item: item[1], reverse=True)[:max_views_per_tooth]
            selected_embeddings = np.stack([item[0] for item in selected])
            selected_confidences = np.asarray([item[1] for item in selected], dtype=np.float32)
            embedding = aggregate_embeddings(selected_embeddings, selected_confidences)
            if embedding.size != feature_dimension:
                raise RuntimeError(
                    f"inconsistent {feature_name} feature dimension for {checkup_uid}/{TOOTH_NAMES[tooth_index]}"
                )
            embeddings[checkup_index, tooth_index] = embedding
            present[checkup_index, tooth_index] = True
            view_counts[checkup_index, tooth_index] = len(selected)
            mean_confidences[checkup_index, tooth_index] = float(selected_confidences.mean())

    patient_ids = np.asarray([checkups[uid].patient_id for uid in checkup_ids])
    checkup_session_ids = np.asarray([checkups[uid].checkup_id for uid in checkup_ids])
    photos_by_checkup: dict[str, list[Photo]] = defaultdict(list)
    for photo in photos:
        photos_by_checkup[photo.checkup_uid].append(photo)
    photo_manifest_json: list[str] = []
    for checkup_uid in checkup_ids:
        checkup_photos = photos_by_checkup[checkup_uid]
        references = tuple(photo.reference for photo in checkup_photos)
        if references != checkups[checkup_uid].photographs:
            raise RuntimeError(f"photograph manifest mismatch for checkup {checkup_uid!r}.")
        photo_manifest_json.append(
            json.dumps(
                [
                    {
                        "reference": photo.reference,
                        "sha256": photo.content_sha256,
                    }
                    for photo in checkup_photos
                ],
                separators=(",", ":"),
                ensure_ascii=False,
            )
        )
    atomic_save_npz(
        path,
        checkup_ids=np.asarray(checkup_ids),
        patient_ids=patient_ids,
        session_ids=checkup_session_ids,
        tooth_names=np.asarray(TOOTH_NAMES),
        embeddings=embeddings,
        present=present,
        view_counts=view_counts,
        mean_confidences=mean_confidences,
        feature_name=np.asarray(feature_name),
        photo_manifest_json=np.asarray(photo_manifest_json),
        segmentation_weights_sha256=np.asarray(normalized_weights_sha256),
        segmentation_imgsz=np.asarray(imgsz, dtype=np.int64),
        segmentation_conf=np.asarray(conf, dtype=np.float64),
        segmentation_iou=np.asarray(iou, dtype=np.float64),
        crop_size=np.asarray(crop_size, dtype=np.int64),
        crop_padding=np.asarray(crop_padding, dtype=np.float64),
        preprocessing_format_version=np.asarray(preprocessing_format_version),
    )
    return {
        "file": path.name,
        "dimension": feature_dimension,
        "checkups_with_features": int(present.any(axis=1).sum()),
        "tooth_slots_present": int(present.sum()),
        "per_tooth_checkups": {
            tooth_name: int(present[:, index].sum()) for index, tooth_name in enumerate(TOOTH_NAMES)
        },
    }


def atomic_write_text(path: Path, value: str) -> None:
    with tempfile.NamedTemporaryFile(
        dir=path.parent,
        mode="w",
        encoding="utf-8",
        newline="",
        delete=False,
    ) as handle:
        handle.write(value)
        temporary = Path(handle.name)
    try:
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def write_quality_csv(path: Path, checkups: dict[str, Checkup], quality: dict[str, CheckupQuality]) -> None:
    with tempfile.NamedTemporaryFile(
        dir=path.parent,
        mode="w",
        encoding="utf-8",
        newline="",
        delete=False,
    ) as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "split",
                "checkup_id",
                "patient_id",
                "session_id",
                "photographs_total",
                "photographs_processed",
                "detections",
                "mean_detection_confidence",
            ]
        )
        for uid in sorted(checkups):
            checkup = checkups[uid]
            row = quality[uid]
            mean_confidence = row.confidence_sum / row.detections if row.detections else 0.0
            writer.writerow(
                [
                    checkup.split,
                    uid,
                    checkup.patient_id,
                    checkup.checkup_id,
                    row.photographs_total,
                    row.photographs_processed,
                    row.detections,
                    f"{mean_confidence:.8f}",
                ]
            )
        temporary = Path(handle.name)
    try:
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def write_audit_crops(output_dir: Path, records: list[CropRecord]) -> tuple[Path, Path] | None:
    if not records:
        return None

    temporary_dir = Path(tempfile.mkdtemp(prefix=".audit_crops_", dir=output_dir.parent))
    try:
        manifest_path = temporary_dir / "manifest.csv"
        with manifest_path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(["file", "tooth", "confidence"])
            for index, record in enumerate(records, start=1):
                tooth_name = TOOTH_NAMES[record.tooth_index]
                file_name = f"{index:03d}_{tooth_name}_{record.confidence:.4f}.jpg"
                Image.fromarray(record.image).save(temporary_dir / file_name, quality=92)
                writer.writerow(
                    [
                        file_name,
                        tooth_name,
                        f"{record.confidence:.8f}",
                    ]
                )

        tile_size = records[0].image.shape[0]
        columns = min(5, len(records))
        rows = (len(records) + columns - 1) // columns
        label_height = 24
        sheet = Image.new("RGB", (columns * tile_size, rows * (tile_size + label_height)), "white")
        draw = ImageDraw.Draw(sheet)
        for index, record in enumerate(records):
            column = index % columns
            row = index // columns
            x = column * tile_size
            y = row * (tile_size + label_height)
            sheet.paste(Image.fromarray(record.image), (x, y))
            draw.text(
                (x + 4, y + tile_size + 4),
                f"{TOOTH_NAMES[record.tooth_index]} {record.confidence:.3f}",
                fill="black",
            )
        contact_sheet_path = output_dir.parent / "audit_contact_sheet.jpg"
        temporary_contact_sheet = temporary_dir.parent / f".{contact_sheet_path.name}.tmp"
        sheet.save(temporary_contact_sheet, format="JPEG", quality=90)

        if output_dir.exists():
            shutil.rmtree(output_dir)
        os.replace(temporary_dir, output_dir)
        os.replace(temporary_contact_sheet, contact_sheet_path)
        return output_dir / "manifest.csv", contact_sheet_path
    finally:
        if temporary_dir.exists():
            shutil.rmtree(temporary_dir)


def main() -> int:
    args = parse_args()
    validate_args(args)
    require_file(args.pairs_csv, "pair CSV")
    require_file(args.weights, "segmentation weights")
    expected_weights_sha256 = normalize_sha256(
        args.expected_weights_sha256,
        "--expected-weights-sha256",
    )
    actual_weights_sha256 = sha256_file(args.weights)
    if actual_weights_sha256 != expected_weights_sha256:
        raise RuntimeError(
            "segmentation weight SHA-256 mismatch: "
            f"expected={expected_weights_sha256}, actual={actual_weights_sha256}"
        )
    resnet_weights_sha256 = None
    if "resnet50" in args.feature_types:
        resnet_weights_sha256 = prepare_resnet_checkpoint(args.resnet_weights)
    checkups, pair_ids = load_selected_checkups(args.pairs_csv, args.split, args.max_pairs)
    photos = resolve_photos(checkups, args.images_root)

    print(
        f"selected_pairs={len(pair_ids)} checkups={len(checkups)} photographs={len(photos)}",
        flush=True,
    )
    if args.validate_only:
        print("validation_only=true")
        return 0

    generation_dir = create_generation_directory(args.output_dir)
    try:
        quality = {
            uid: CheckupQuality(photographs_total=len(checkup.photographs))
            for uid, checkup in checkups.items()
        }
        feature_views, audit_crops = collect_features(args, photos, quality)

        feature_summaries: dict[str, object] = {}
        for feature_name in args.feature_types:
            feature_path = generation_dir / f"features_{feature_name}.npz"
            feature_summaries[feature_name] = write_feature_file(
                feature_path,
                feature_name,
                checkups,
                photos,
                feature_views[feature_name],
                args.max_views_per_tooth,
                segmentation_weights_sha256=actual_weights_sha256,
                imgsz=args.imgsz,
                conf=args.conf,
                iou=args.iou,
                crop_size=args.crop_size,
                crop_padding=args.crop_padding,
                preprocessing_format_version=PREPROCESSING_FORMAT_VERSION,
            )

        write_quality_csv(generation_dir / "quality.csv", checkups, quality)
        audit_outputs = write_audit_crops(generation_dir / "audit_crops", audit_crops)
        detection_count = sum(row.detections for row in quality.values())
        summary = {
            "pairs_csv_name": args.pairs_csv.name,
            "weights_name": args.weights.name,
            "weights_sha256": actual_weights_sha256,
            "split": args.split,
            "max_pairs": args.max_pairs,
            "selected_pairs": len(pair_ids),
            "checkups": len(checkups),
            "photographs": len(photos),
            "detections": detection_count,
            "checkups_with_detections": sum(row.detections > 0 for row in quality.values()),
            "audit_crops": len(audit_crops),
            "settings": {
                "device": args.device,
                "imgsz": args.imgsz,
                "conf": args.conf,
                "iou": args.iou,
                "source_chunk_size": args.source_chunk_size,
                "feature_batch_size": args.feature_batch_size,
                "crop_size": args.crop_size,
                "crop_padding": args.crop_padding,
                "preprocessing_format_version": PREPROCESSING_FORMAT_VERSION,
                "max_views_per_tooth": args.max_views_per_tooth,
            },
            "features": feature_summaries,
            "resnet50_weights": RESNET_WEIGHTS_NAME if "resnet50" in args.feature_types else None,
            "resnet50_weights_sha256": resnet_weights_sha256,
        }
        atomic_write_text(
            generation_dir / "summary.json",
            json.dumps(summary, indent=2, ensure_ascii=False) + "\n",
        )
        publish_generation(generation_dir, args.output_dir)
    finally:
        discard_generation(generation_dir)

    quality_path = args.output_dir / "quality.csv"
    summary_path = args.output_dir / "summary.json"
    print(f"quality: {quality_path}")
    if audit_outputs is not None:
        print(f"audit_manifest: {args.output_dir / 'audit_crops' / 'manifest.csv'}")
        print(f"audit_contact_sheet: {args.output_dir / 'audit_contact_sheet.jpg'}")
    print(f"summary: {summary_path}")
    print(
        f"detections={summary['detections']} "
        f"checkups_with_detections={summary['checkups_with_detections']}/{summary['checkups']}"
    )
    for feature_name, feature_summary in feature_summaries.items():
        print(
            f"{feature_name}: file={feature_summary['file']} "
            f"checkups_with_features={feature_summary['checkups_with_features']} "
            f"tooth_slots_present={feature_summary['tooth_slots_present']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
