from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import random
import shutil
import subprocess
import zipfile
from collections import defaultdict
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from code_photos import parse_photographs, resolve_photo_reference, sha256_file
from build_code_pair_manifest import split_patients
from output_directory import create_generation_directory, discard_generation, publish_generation


REQUIRED_CHECKUP_COLUMNS = (
    "split",
    "patient_id",
    "checkup_id",
    "checkup_uid",
    "photograph_count",
    "photographs",
    "source_row_number",
)
ALLOWED_SPLITS = ("train", "val", "test")
SELECTED_SPLITS = ("train", "val")
EXPECTED_SOURCE_RATIOS = {"train": 0.70, "val": 0.15, "test": 0.15}
ALL_TOOTH_NAMES = (
    "R1",
    "R2",
    "R3",
    "R4",
    "R5",
    "R6",
    "R7",
    "L1",
    "L2",
    "L3",
    "L4",
    "L5",
    "L6",
    "L7",
)
ANNOTATED_TOOTH_NAMES = ("R1", "R2", "R3", "L1", "L2", "L3")
SUPPORTED_IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png"}
MANIFEST_COLUMNS = (
    "split",
    "image_name",
    "patient_token",
    "checkup_token",
    "source_patient_id",
    "source_checkup_id",
    "source_row_number",
    "source_photo_reference",
    "source_sha256",
    "annotation_status",
    "view_tag",
    "lighting_tag",
    "oral_condition_tag",
    "notes",
)


@dataclass(frozen=True)
class Checkup:
    split: str
    patient_id: str
    checkup_id: str
    photographs: tuple[str, ...]
    source_row_number: int

    @property
    def uid(self) -> str:
        return f"{self.patient_id}:{self.checkup_id}"


@dataclass(frozen=True)
class SelectedPhoto:
    split: str
    image_name: str
    patient_token: str
    checkup_token: str
    source_patient_id: str
    source_checkup_id: str
    source_row_number: int
    source_photo_reference: str
    source_path: Path
    source_sha256: str


def find_project_root(start: Path) -> Path:
    for path in (start, *start.parents):
        if (path / "pyproject.toml").exists():
            return path
    raise RuntimeError(f"project root not found from: {start}")


def validate_output_location(output_dir: Path, repo_root: Path) -> None:
    resolved_output = output_dir.resolve()
    resolved_repo = repo_root.resolve()
    if not resolved_output.is_relative_to(resolved_repo):
        return

    relative_output = resolved_output.relative_to(resolved_repo)
    tracked_result = subprocess.run(
        ["git", "ls-files", "--cached", "--", relative_output.as_posix()],
        cwd=resolved_repo,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if tracked_result.returncode != 0:
        raise RuntimeError(
            f"failed to inspect tracked output files: {tracked_result.stderr.strip()}"
        )
    if tracked_result.stdout.strip() != "":
        raise RuntimeError(
            f"output directory contains tracked files and cannot store private data: "
            f"{resolved_output}"
        )

    result = subprocess.run(
        ["git", "check-ignore", "--quiet", "--no-index", str(resolved_output)],
        cwd=resolved_repo,
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode == 0:
        return
    if result.returncode == 1:
        raise RuntimeError(
            f"output directory inside the repository must be Git-ignored: {resolved_output}"
        )
    raise RuntimeError(
        f"failed to verify whether output directory is Git-ignored: {result.stderr.strip()}"
    )


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    repo_root = find_project_root(Path(__file__).resolve())
    parser = argparse.ArgumentParser(
        description="Prepare a patient-separated COde image batch for CVAT polygon annotation."
    )
    parser.add_argument(
        "--checkups-csv",
        type=Path,
        required=True,
        help="checkups.csv generated by build_code_pair_manifest.py.",
    )
    parser.add_argument(
        "--source-summary",
        type=Path,
        required=True,
        help="summary.json generated alongside checkups.csv.",
    )
    parser.add_argument(
        "--images-root",
        type=Path,
        required=True,
        help="Extracted COde root containing Images/Photographs.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=(
            repo_root
            / "01_stage1_real_image_extraction"
            / "datasets"
            / "dataset_real"
            / "code_annotation"
        ),
        help="Ignored directory for copied images, manifest, labels, and CVAT ZIP files.",
    )
    parser.add_argument("--seed", type=int, default=42, help="Deterministic selection seed.")
    parser.add_argument(
        "--expected-source-seed",
        type=int,
        default=42,
        help="Required patient-split seed recorded in the source summary.",
    )
    parser.add_argument(
        "--train-checkups",
        type=int,
        default=10,
        help="Number of train patients/checkups to select.",
    )
    parser.add_argument(
        "--val-checkups",
        type=int,
        default=5,
        help="Number of val patients/checkups to select.",
    )
    parser.add_argument(
        "--photos-per-checkup",
        type=int,
        default=4,
        help="Unique-content photographs selected from each checkup.",
    )
    return parser.parse_args(argv)


def validate_args(args: argparse.Namespace) -> None:
    if args.train_checkups <= 0:
        raise RuntimeError("--train-checkups must be positive.")
    if args.val_checkups <= 0:
        raise RuntimeError("--val-checkups must be positive.")
    if args.photos_per_checkup <= 0:
        raise RuntimeError("--photos-per-checkup must be positive.")


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise RuntimeError(f"{label} was not found: {path}")


def read_required_file(path: Path, label: str) -> bytes:
    require_file(path, label)
    return path.read_bytes()


def sha256_bytes(document: bytes) -> str:
    return hashlib.sha256(document).hexdigest()


def load_source_split_summary(
    path: Path,
    document_bytes: bytes,
    *,
    expected_seed: int,
    expected_checkups_sha256: str,
) -> dict[str, object]:
    try:
        document = json.loads(document_bytes.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as error:
        raise RuntimeError(f"source summary is not valid UTF-8 JSON: {path}") from error
    if not isinstance(document, dict):
        raise RuntimeError(f"source summary root must be an object: {path}")
    try:
        seed = document["seed"]
        ratios = document["ratios"]
        checkups_csv_sha256 = document["checkups_csv_sha256"]
    except KeyError as error:
        raise RuntimeError(f"source summary is missing required key: {error.args[0]}") from error

    if not isinstance(seed, int) or isinstance(seed, bool):
        raise RuntimeError("source split seed must be an integer.")
    if seed != expected_seed:
        raise RuntimeError(
            f"source split seed does not match: expected={expected_seed}, actual={seed}"
        )
    if not isinstance(checkups_csv_sha256, str):
        raise RuntimeError("source checkups CSV SHA-256 must be a string.")
    if checkups_csv_sha256 != expected_checkups_sha256:
        raise RuntimeError(
            "source checkups CSV SHA-256 does not match: "
            f"expected={expected_checkups_sha256}, actual={checkups_csv_sha256}"
        )
    if not isinstance(ratios, dict):
        raise RuntimeError("source split ratios must be an object.")
    if set(ratios) != set(EXPECTED_SOURCE_RATIOS):
        raise RuntimeError(
            f"source split ratio keys do not match: expected={sorted(EXPECTED_SOURCE_RATIOS)}, "
            f"actual={sorted(ratios)}"
        )
    for split, expected_ratio in EXPECTED_SOURCE_RATIOS.items():
        ratio = ratios[split]
        if not isinstance(ratio, (int, float)) or isinstance(ratio, bool):
            raise RuntimeError(f"source split ratio must be numeric: {split}")
        if ratio != expected_ratio:
            raise RuntimeError(
                f"source split ratio does not match for {split}: "
                f"expected={expected_ratio}, actual={ratio}"
            )
    return {"seed": seed, "ratios": dict(EXPECTED_SOURCE_RATIOS)}


def clean_required(value: str | None, column: str, row_number: int) -> str:
    if value is None:
        raise RuntimeError(f"{column} is missing at CSV row {row_number}.")
    cleaned = value.strip()
    if cleaned == "":
        raise RuntimeError(f"{column} is empty at CSV row {row_number}.")
    return cleaned


def validate_header(fieldnames: list[str] | None, path: Path) -> None:
    if fieldnames is None:
        raise RuntimeError(f"checkup CSV has no header: {path}")
    if len(fieldnames) != len(set(fieldnames)):
        raise RuntimeError(f"checkup CSV has duplicate columns: {path}")
    missing = [column for column in REQUIRED_CHECKUP_COLUMNS if column not in fieldnames]
    if missing:
        raise RuntimeError(f"checkup CSV is missing required columns {missing}: {path}")


def parse_positive_integer(value: str | None, column: str, row_number: int) -> int:
    cleaned = clean_required(value, column, row_number)
    try:
        parsed = int(cleaned)
    except ValueError as exc:
        raise RuntimeError(f"{column} must be an integer at CSV row {row_number}: {cleaned!r}") from exc
    if parsed <= 0:
        raise RuntimeError(f"{column} must be positive at CSV row {row_number}: {parsed}")
    return parsed


def load_checkups(path: Path, document_bytes: bytes) -> list[Checkup]:
    try:
        document = document_bytes.decode("utf-8-sig")
    except UnicodeDecodeError as error:
        raise RuntimeError(f"checkup CSV is not valid UTF-8: {path}") from error
    with io.StringIO(document, newline="") as handle:
        reader = csv.DictReader(handle)
        validate_header(reader.fieldnames, path)
        checkups: list[Checkup] = []
        seen_uids: dict[str, int] = {}
        split_by_patient: dict[str, str] = {}
        for row_number, row in enumerate(reader, start=2):
            split = clean_required(row["split"], "split", row_number)
            if split not in ALLOWED_SPLITS:
                raise RuntimeError(f"unsupported split at CSV row {row_number}: {split!r}")
            patient_id = clean_required(row["patient_id"], "patient_id", row_number)
            checkup_id = clean_required(row["checkup_id"], "checkup_id", row_number)
            checkup_uid = clean_required(row["checkup_uid"], "checkup_uid", row_number)
            expected_uid = f"{patient_id}:{checkup_id}"
            if checkup_uid != expected_uid:
                raise RuntimeError(
                    f"checkup_uid mismatch at CSV row {row_number}: "
                    f"expected={expected_uid!r}, actual={checkup_uid!r}"
                )
            if checkup_uid in seen_uids:
                raise RuntimeError(
                    f"duplicate checkup_uid at CSV row {row_number}; "
                    f"first seen at row {seen_uids[checkup_uid]}: {checkup_uid!r}"
                )
            seen_uids[checkup_uid] = row_number

            photographs = parse_photographs(
                clean_required(row["photographs"], "photographs", row_number),
                "photographs",
                row_number,
            )
            photograph_count = parse_positive_integer(
                row["photograph_count"],
                "photograph_count",
                row_number,
            )
            if photograph_count != len(photographs):
                raise RuntimeError(
                    f"photograph_count mismatch at CSV row {row_number}: "
                    f"expected={len(photographs)}, actual={photograph_count}"
                )
            source_row_number = parse_positive_integer(
                row["source_row_number"],
                "source_row_number",
                row_number,
            )

            if patient_id in split_by_patient and split_by_patient[patient_id] != split:
                raise RuntimeError(
                    f"patient {patient_id!r} is assigned to multiple splits: "
                    f"{split_by_patient[patient_id]!r}, {split!r}"
                )
            split_by_patient[patient_id] = split
            checkups.append(
                Checkup(
                    split=split,
                    patient_id=patient_id,
                    checkup_id=checkup_id,
                    photographs=photographs,
                    source_row_number=source_row_number,
                )
            )
    if not checkups:
        raise RuntimeError(f"checkup CSV has no rows: {path}")
    return checkups


def validate_patient_splits(checkups: list[Checkup], seed: int) -> None:
    patient_ids = list({checkup.patient_id for checkup in checkups})
    expected_by_patient = split_patients(
        patient_ids,
        train_ratio=EXPECTED_SOURCE_RATIOS["train"],
        val_ratio=EXPECTED_SOURCE_RATIOS["val"],
        rng=random.Random(seed),
    )
    for checkup in checkups:
        expected_split = expected_by_patient[checkup.patient_id]
        if checkup.split != expected_split:
            raise RuntimeError(
                f"patient split does not match source seed for {checkup.patient_id!r}: "
                f"expected={expected_split!r}, actual={checkup.split!r}"
            )


def stable_rank(seed: int, *values: str) -> str:
    payload = "\0".join((str(seed), *values)).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def rank_values(values: Sequence[str], seed: int, *scope: str) -> list[str]:
    return sorted(values, key=lambda value: (stable_rank(seed, *scope, value), value))


def collect_split_content_hashes(
    checkups: list[Checkup],
    *,
    split: str,
    images_root: Path,
) -> set[str]:
    content_hashes: set[str] = set()
    for checkup in checkups:
        if checkup.split != split:
            continue
        for reference in checkup.photographs:
            source_path = resolve_photo_reference(images_root, reference)
            if source_path.suffix.lower() not in SUPPORTED_IMAGE_SUFFIXES:
                raise RuntimeError(f"unsupported photograph suffix: {source_path}")
            content_hashes.add(sha256_file(source_path))
    return content_hashes


def select_split(
    checkups: list[Checkup],
    *,
    split: str,
    checkup_count: int,
    photos_per_checkup: int,
    seed: int,
    images_root: Path,
    used_content_hashes: set[str],
) -> list[SelectedPhoto]:
    checkups_by_patient: dict[str, list[Checkup]] = defaultdict(list)
    for checkup in checkups:
        if checkup.split == split:
            checkups_by_patient[checkup.patient_id].append(checkup)

    selected: list[SelectedPhoto] = []
    selected_checkups = 0
    patient_ids = rank_values(tuple(checkups_by_patient), seed, split, "patient")
    for patient_id in patient_ids:
        candidate_checkups = sorted(
            checkups_by_patient[patient_id],
            key=lambda item: (
                stable_rank(seed, split, patient_id, "checkup", item.checkup_id),
                item.checkup_id,
            ),
        )
        selected_for_patient: list[tuple[Checkup, str, Path, str]] | None = None
        for checkup in candidate_checkups:
            if len(checkup.photographs) < photos_per_checkup:
                continue
            candidate_photos: list[tuple[Checkup, str, Path, str]] = []
            local_hashes: set[str] = set()
            ranked_references = rank_values(
                checkup.photographs,
                seed,
                split,
                patient_id,
                checkup.checkup_id,
                "photo",
            )
            for reference in ranked_references:
                source_path = resolve_photo_reference(images_root, reference)
                suffix = source_path.suffix.lower()
                if suffix not in SUPPORTED_IMAGE_SUFFIXES:
                    raise RuntimeError(f"unsupported photograph suffix: {source_path}")
                content_sha256 = sha256_file(source_path)
                if content_sha256 in used_content_hashes or content_sha256 in local_hashes:
                    continue
                candidate_photos.append((checkup, reference, source_path, content_sha256))
                local_hashes.add(content_sha256)
                if len(candidate_photos) == photos_per_checkup:
                    selected_for_patient = candidate_photos
                    break
            if selected_for_patient is not None:
                break
        if selected_for_patient is None:
            continue

        selected_checkups += 1
        patient_token = f"{split}_patient_{selected_checkups:04d}"
        checkup_token = f"{split}_checkup_{selected_checkups:04d}"
        for photo_index, (checkup, reference, source_path, content_sha256) in enumerate(
            selected_for_patient,
            start=1,
        ):
            image_name = (
                f"code_{split}_{selected_checkups:04d}_{photo_index:02d}"
                f"{source_path.suffix.lower()}"
            )
            selected.append(
                SelectedPhoto(
                    split=split,
                    image_name=image_name,
                    patient_token=patient_token,
                    checkup_token=checkup_token,
                    source_patient_id=checkup.patient_id,
                    source_checkup_id=checkup.checkup_id,
                    source_row_number=checkup.source_row_number,
                    source_photo_reference=reference,
                    source_path=source_path,
                    source_sha256=content_sha256,
                )
            )
            used_content_hashes.add(content_sha256)
        if selected_checkups == checkup_count:
            break

    if selected_checkups != checkup_count:
        raise RuntimeError(
            f"not enough eligible {split} patients/checkups: "
            f"required={checkup_count}, selected={selected_checkups}, "
            f"photos_per_checkup={photos_per_checkup}"
        )
    return selected


def write_manifest(path: Path, selected: list[SelectedPhoto]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=MANIFEST_COLUMNS, lineterminator="\n")
        writer.writeheader()
        for photo in selected:
            writer.writerow(
                {
                    "split": photo.split,
                    "image_name": photo.image_name,
                    "patient_token": photo.patient_token,
                    "checkup_token": photo.checkup_token,
                    "source_patient_id": photo.source_patient_id,
                    "source_checkup_id": photo.source_checkup_id,
                    "source_row_number": photo.source_row_number,
                    "source_photo_reference": photo.source_photo_reference,
                    "source_sha256": photo.source_sha256,
                    "annotation_status": "pending",
                    "view_tag": "",
                    "lighting_tag": "",
                    "oral_condition_tag": "",
                    "notes": "",
                }
            )


def write_labels_json(path: Path) -> None:
    labels = [
        {"name": name, "type": "polygon", "attributes": []} for name in ALL_TOOTH_NAMES
    ]
    path.write_text(
        json.dumps(labels, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def write_deterministic_zip(path: Path, image_dir: Path, selected: list[SelectedPhoto]) -> None:
    with zipfile.ZipFile(
        path,
        mode="w",
        compression=zipfile.ZIP_STORED,
    ) as archive:
        for photo in selected:
            info = zipfile.ZipInfo(
                filename=f"images/{photo.image_name}",
                date_time=(1980, 1, 1, 0, 0, 0),
            )
            info.create_system = 3
            info.compress_type = zipfile.ZIP_STORED
            info.external_attr = 0o100644 << 16
            archive.writestr(
                info,
                (image_dir / photo.image_name).read_bytes(),
            )


def build_outputs(
    output_dir: Path,
    selected: list[SelectedPhoto],
    *,
    checkups_csv: Path,
    source_split: dict[str, object],
    checkups_csv_sha256: str,
    source_summary_sha256: str,
    test_content_hashes: int,
    seed: int,
    train_checkups: int,
    val_checkups: int,
    photos_per_checkup: int,
) -> dict[str, object]:
    generation_dir = create_generation_directory(output_dir)
    try:
        image_dir = generation_dir / "images"
        image_dir.mkdir()
        for photo in selected:
            target_path = image_dir / photo.image_name
            shutil.copy2(photo.source_path, target_path)
            copied_sha256 = sha256_file(target_path)
            if copied_sha256 != photo.source_sha256:
                raise RuntimeError(
                    f"photograph changed while copying: {photo.source_photo_reference!r}, "
                    f"expected={photo.source_sha256}, actual={copied_sha256}"
                )

        manifest_path = generation_dir / "annotation_manifest.csv"
        labels_path = generation_dir / "cvat_labels.json"
        write_manifest(manifest_path, selected)
        write_labels_json(labels_path)

        archive_paths: dict[str, Path] = {}
        for split in SELECTED_SPLITS:
            archive_path = generation_dir / f"cvat_{split}_images.zip"
            split_photos = [photo for photo in selected if photo.split == split]
            write_deterministic_zip(archive_path, image_dir, split_photos)
            archive_paths[split] = archive_path

        selected_images_by_split = {
            split: sum(photo.split == split for photo in selected) for split in SELECTED_SPLITS
        }
        summary: dict[str, object] = {
            "checkups_csv_name": checkups_csv.name,
            "checkups_csv_sha256": checkups_csv_sha256,
            "source_summary_sha256": source_summary_sha256,
            "source_split": source_split,
            "test_content_hashes_excluded": test_content_hashes,
            "seed": seed,
            "selected_images": len(selected),
            "selected_images_by_split": selected_images_by_split,
            "selected_checkups": {
                "train": train_checkups,
                "val": val_checkups,
            },
            "photos_per_checkup": photos_per_checkup,
            "unique_source_patients": len({photo.source_patient_id for photo in selected}),
            "unique_source_checkups": len(
                {(photo.source_patient_id, photo.source_checkup_id) for photo in selected}
            ),
            "unique_content_hashes": len({photo.source_sha256 for photo in selected}),
            "class_names": list(ALL_TOOTH_NAMES),
            "annotation_classes": list(ANNOTATED_TOOTH_NAMES),
            "manifest_sha256": sha256_file(manifest_path),
            "cvat_archive_sha256_by_split": {
                split: sha256_file(archive_paths[split]) for split in SELECTED_SPLITS
            },
        }
        (generation_dir / "summary.json").write_text(
            json.dumps(summary, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        publish_generation(generation_dir, output_dir)
    finally:
        discard_generation(generation_dir)
    return summary


def run(args: argparse.Namespace) -> dict[str, object]:
    validate_args(args)
    validate_output_location(args.output_dir, find_project_root(Path(__file__).resolve()))
    checkups_document = read_required_file(args.checkups_csv, "checkup CSV")
    source_summary_document = read_required_file(args.source_summary, "source summary")
    checkups_csv_sha256 = sha256_bytes(checkups_document)
    source_summary_sha256 = sha256_bytes(source_summary_document)
    source_split = load_source_split_summary(
        args.source_summary,
        source_summary_document,
        expected_seed=args.expected_source_seed,
        expected_checkups_sha256=checkups_csv_sha256,
    )
    checkups = load_checkups(args.checkups_csv, checkups_document)
    validate_patient_splits(checkups, args.expected_source_seed)
    used_content_hashes = collect_split_content_hashes(
        checkups,
        split="test",
        images_root=args.images_root,
    )
    test_content_hashes = len(used_content_hashes)
    selected: list[SelectedPhoto] = []
    selected.extend(
        select_split(
            checkups,
            split="train",
            checkup_count=args.train_checkups,
            photos_per_checkup=args.photos_per_checkup,
            seed=args.seed,
            images_root=args.images_root,
            used_content_hashes=used_content_hashes,
        )
    )
    selected.extend(
        select_split(
            checkups,
            split="val",
            checkup_count=args.val_checkups,
            photos_per_checkup=args.photos_per_checkup,
            seed=args.seed,
            images_root=args.images_root,
            used_content_hashes=used_content_hashes,
        )
    )
    return build_outputs(
        args.output_dir,
        selected,
        checkups_csv=args.checkups_csv,
        source_split=source_split,
        checkups_csv_sha256=checkups_csv_sha256,
        source_summary_sha256=source_summary_sha256,
        test_content_hashes=test_content_hashes,
        seed=args.seed,
        train_checkups=args.train_checkups,
        val_checkups=args.val_checkups,
        photos_per_checkup=args.photos_per_checkup,
    )


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    summary = run(args)
    print(f"manifest: {args.output_dir / 'annotation_manifest.csv'}")
    print(f"labels: {args.output_dir / 'cvat_labels.json'}")
    for split in SELECTED_SPLITS:
        print(f"cvat_{split}_images: {args.output_dir / f'cvat_{split}_images.zip'}")
    print(f"summary: {args.output_dir / 'summary.json'}")
    print(
        f"selected_images={summary['selected_images']} "
        f"unique_patients={summary['unique_source_patients']} "
        f"unique_checkups={summary['unique_source_checkups']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
