from __future__ import annotations

import argparse
import csv
import json
import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from numbers import Real
from pathlib import Path
from typing import Protocol

import numpy as np

from code_photos import normalize_sha256, parse_photographs, resolve_photo_reference, sha256_file
from matching_core import TOOTH_NAMES, score_pair
from output_directory import create_generation_directory, discard_generation, publish_generation


EXPECTED_TOOTH_NAMES = ("R1", "R2", "R3", "L1", "L2", "L3")
REQUIRED_PAIR_COLUMNS = (
    "split",
    "pair_id",
    "is_genuine",
    "template_id",
    "query_id",
    "template_patient_id",
    "query_patient_id",
    "template_checkup_id",
    "query_checkup_id",
    "template_photographs",
    "query_photographs",
)
REQUIRED_FEATURE_ARRAYS = (
    "checkup_ids",
    "patient_ids",
    "tooth_names",
    "embeddings",
    "present",
    "photo_manifest_json",
)
SCORE_COLUMNS = (
    "query_id",
    "template_id",
    "query_subject_id",
    "template_subject_id",
    "query_session_id",
    "template_session_id",
    "is_genuine",
    "fused_score",
    "pair_id",
    "split",
    "common_teeth",
    "per_tooth_scores",
)
SKIPPED_COLUMNS = (*REQUIRED_PAIR_COLUMNS, "common_teeth", "reason")


class MatchingResultLike(Protocol):
    fused_score: float
    per_tooth_scores: Mapping[str, float]
    common_teeth: int | tuple[str, ...]


@dataclass(frozen=True)
class PairRecord:
    split: str
    pair_id: str
    is_genuine: bool
    template_id: str
    query_id: str
    template_patient_id: str
    query_patient_id: str
    template_checkup_id: str
    query_checkup_id: str
    template_photographs: tuple[str, ...]
    query_photographs: tuple[str, ...]
    source_row_number: int


@dataclass(frozen=True)
class FeatureStore:
    patient_ids: tuple[str, ...]
    embeddings: np.ndarray
    present: np.ndarray
    photo_fingerprints: tuple[tuple[PhotoFingerprint, ...], ...]
    index_by_checkup_id: dict[str, int]


@dataclass(frozen=True)
class PhotoFingerprint:
    reference: str
    sha256: str


@dataclass(frozen=True)
class ScoredPair:
    pair: PairRecord
    fused_score: float
    per_tooth_scores: dict[str, float]
    common_teeth: int


@dataclass(frozen=True)
class SkippedPair:
    pair: PairRecord
    common_teeth: int | None
    reason: str


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Score COde authentication pairs from an extracted feature NPZ."
    )
    parser.add_argument(
        "--pairs-csv",
        type=Path,
        required=True,
        help="Pair manifest generated by build_code_pair_manifest.py.",
    )
    parser.add_argument(
        "--features-npz",
        type=Path,
        required=True,
        help="Extracted per-checkup feature NPZ.",
    )
    parser.add_argument(
        "--images-root",
        type=Path,
        required=True,
        help="Extracted COde root containing Images/Photographs.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory for scores.csv, skipped_pairs.csv, and summary.json.",
    )
    parser.add_argument("--split", default="test", help="Pair split to score.")
    parser.add_argument(
        "--max-pairs",
        type=int,
        default=0,
        help="Maximum selected rows after split filtering; 0 uses all rows.",
    )
    parser.add_argument(
        "--min-common-teeth",
        type=int,
        default=1,
        help="Minimum number of teeth present in both checkups.",
    )
    return parser.parse_args(argv)


def validate_args(args: argparse.Namespace) -> None:
    if args.max_pairs < 0:
        raise RuntimeError("--max-pairs must be non-negative.")
    if not 1 <= args.min_common_teeth <= len(EXPECTED_TOOTH_NAMES):
        raise RuntimeError(
            f"--min-common-teeth must be from 1 to {len(EXPECTED_TOOTH_NAMES)}."
        )
    if args.split.strip() == "":
        raise RuntimeError("--split must not be empty.")


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise RuntimeError(f"{label} was not found: {path}")


def clean_required(value: str | None, column: str, row_number: int) -> str:
    if value is None:
        raise RuntimeError(f"{column} is missing at CSV row {row_number}.")
    cleaned = value.strip()
    if cleaned == "":
        raise RuntimeError(f"{column} is empty at CSV row {row_number}.")
    return cleaned


def parse_bool(value: str, row_number: int) -> bool:
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "genuine"}:
        return True
    if normalized in {"0", "false", "no", "impostor"}:
        return False
    raise RuntimeError(
        f"is_genuine must be boolean-like at CSV row {row_number}: {value!r}"
    )


def validate_pair_header(fieldnames: list[str] | None, path: Path) -> None:
    if fieldnames is None:
        raise RuntimeError(f"pair CSV has no header: {path}")
    if len(fieldnames) != len(set(fieldnames)):
        raise RuntimeError(f"pair CSV has duplicate columns: {path}")
    missing = [column for column in REQUIRED_PAIR_COLUMNS if column not in fieldnames]
    if missing:
        raise RuntimeError(f"pair CSV is missing required columns {missing}: {path}")


def parse_pair_row(row: dict[str, str | None], row_number: int) -> PairRecord:
    values = {
        column: clean_required(row[column], column, row_number)
        for column in REQUIRED_PAIR_COLUMNS
    }
    pair = PairRecord(
        split=values["split"],
        pair_id=values["pair_id"],
        is_genuine=parse_bool(values["is_genuine"], row_number),
        template_id=values["template_id"],
        query_id=values["query_id"],
        template_patient_id=values["template_patient_id"],
        query_patient_id=values["query_patient_id"],
        template_checkup_id=values["template_checkup_id"],
        query_checkup_id=values["query_checkup_id"],
        template_photographs=parse_photographs(
            values["template_photographs"],
            "template_photographs",
            row_number,
        ),
        query_photographs=parse_photographs(
            values["query_photographs"],
            "query_photographs",
            row_number,
        ),
        source_row_number=row_number,
    )
    validate_pair_metadata(pair)
    return pair


def validate_pair_metadata(pair: PairRecord) -> None:
    expected_template_id = f"{pair.template_patient_id}:{pair.template_checkup_id}"
    if pair.template_id != expected_template_id:
        raise RuntimeError(
            f"template_id mismatch at CSV row {pair.source_row_number}: "
            f"expected={expected_template_id!r}, actual={pair.template_id!r}"
        )
    expected_query_id = f"{pair.query_patient_id}:{pair.query_checkup_id}"
    if pair.query_id != expected_query_id:
        raise RuntimeError(
            f"query_id mismatch at CSV row {pair.source_row_number}: "
            f"expected={expected_query_id!r}, actual={pair.query_id!r}"
        )

    same_patient = pair.template_patient_id == pair.query_patient_id
    if pair.is_genuine and not same_patient:
        raise RuntimeError(
            f"genuine pair has different patient IDs at CSV row {pair.source_row_number}."
        )
    if not pair.is_genuine and same_patient:
        raise RuntimeError(
            f"impostor pair has the same patient ID at CSV row {pair.source_row_number}."
        )


def load_selected_pairs(path: Path, split: str, max_pairs: int) -> list[PairRecord]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        validate_pair_header(reader.fieldnames, path)
        selected: list[PairRecord] = []
        seen_pair_ids: dict[str, int] = {}
        for row_number, row in enumerate(reader, start=2):
            pair = parse_pair_row(row, row_number)
            if pair.pair_id in seen_pair_ids:
                raise RuntimeError(
                    f"duplicate pair_id at CSV row {row_number}; "
                    f"first seen at row {seen_pair_ids[pair.pair_id]}: {pair.pair_id!r}"
                )
            seen_pair_ids[pair.pair_id] = row_number
            if pair.split == split and (max_pairs == 0 or len(selected) < max_pairs):
                selected.append(pair)

    if not selected:
        raise RuntimeError(f"no pair rows found for split {split!r}: {path}")
    return selected


def load_feature_arrays(path: Path) -> dict[str, np.ndarray]:
    try:
        archive = np.load(path, allow_pickle=False)
    except (OSError, ValueError) as exc:
        raise RuntimeError(f"failed to load feature NPZ: {path}") from exc
    if not isinstance(archive, np.lib.npyio.NpzFile):
        raise RuntimeError(f"feature input must be an NPZ archive: {path}")

    try:
        missing = [name for name in REQUIRED_FEATURE_ARRAYS if name not in archive.files]
        if missing:
            raise RuntimeError(f"feature NPZ is missing required arrays {missing}: {path}")
        try:
            return {name: np.asarray(archive[name]) for name in REQUIRED_FEATURE_ARRAYS}
        except ValueError as exc:
            raise RuntimeError(f"failed to read required arrays from feature NPZ: {path}") from exc
    finally:
        archive.close()


def parse_string_array(array: np.ndarray, name: str) -> tuple[str, ...]:
    if array.dtype.kind not in {"U", "S"}:
        raise RuntimeError(f"{name} must have a string dtype; got {array.dtype}.")

    parsed: list[str] = []
    for index, value in enumerate(array.tolist()):
        if isinstance(value, bytes):
            try:
                decoded = value.decode("utf-8")
            except UnicodeDecodeError as exc:
                raise RuntimeError(f"{name}[{index}] is not valid UTF-8.") from exc
        elif isinstance(value, str):
            decoded = value
        else:
            raise RuntimeError(f"{name}[{index}] is not a string: {value!r}")
        cleaned = decoded.strip()
        if cleaned == "":
            raise RuntimeError(f"{name}[{index}] is empty.")
        parsed.append(cleaned)
    return tuple(parsed)


def parse_photo_fingerprints(
    array: np.ndarray,
    checkup_ids: tuple[str, ...],
) -> tuple[tuple[PhotoFingerprint, ...], ...]:
    if array.shape != (len(checkup_ids),):
        raise RuntimeError(
            f"photo_manifest_json must have shape [{len(checkup_ids)}]; got {array.shape}."
        )
    encoded_manifests = parse_string_array(array, "photo_manifest_json")
    manifests: list[tuple[PhotoFingerprint, ...]] = []
    for index, (checkup_id, encoded) in enumerate(
        zip(checkup_ids, encoded_manifests, strict=True)
    ):
        try:
            decoded = json.loads(encoded)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                f"photo_manifest_json[{index}] is not valid JSON for checkup {checkup_id!r}."
            ) from exc
        if not isinstance(decoded, list) or not decoded:
            raise RuntimeError(
                f"photo_manifest_json[{index}] must be a non-empty JSON array."
            )

        fingerprints: list[PhotoFingerprint] = []
        seen_references: set[str] = set()
        for photo_index, item in enumerate(decoded):
            label = f"photo_manifest_json[{index}][{photo_index}]"
            if not isinstance(item, dict) or set(item) != {"reference", "sha256"}:
                raise RuntimeError(f"{label} must contain only reference and sha256.")
            reference_value = item["reference"]
            if not isinstance(reference_value, str):
                raise RuntimeError(f"{label}.reference must be a string.")
            parsed_references = parse_photographs(reference_value, f"{label}.reference", index + 1)
            if len(parsed_references) != 1 or parsed_references[0] != reference_value:
                raise RuntimeError(f"{label}.reference must contain one normalized reference.")
            if reference_value in seen_references:
                raise RuntimeError(f"duplicate photograph reference in {label}: {reference_value!r}")
            seen_references.add(reference_value)

            hash_value = item["sha256"]
            if not isinstance(hash_value, str):
                raise RuntimeError(f"{label}.sha256 must be a string.")
            fingerprints.append(
                PhotoFingerprint(
                    reference=reference_value,
                    sha256=normalize_sha256(hash_value, f"{label}.sha256"),
                )
            )
        manifests.append(tuple(fingerprints))
    return tuple(manifests)


def validate_core_tooth_order() -> None:
    core_tooth_names = tuple(TOOTH_NAMES)
    if core_tooth_names != EXPECTED_TOOTH_NAMES:
        raise RuntimeError(
            "matching_core.TOOTH_NAMES has an unexpected order; "
            f"expected={EXPECTED_TOOTH_NAMES}, actual={core_tooth_names}"
        )


def build_feature_store(path: Path) -> FeatureStore:
    validate_core_tooth_order()
    arrays = load_feature_arrays(path)
    checkup_ids_array = arrays["checkup_ids"]
    patient_ids_array = arrays["patient_ids"]
    tooth_names_array = arrays["tooth_names"]
    embeddings = arrays["embeddings"]
    present = arrays["present"]
    photo_manifest_json = arrays["photo_manifest_json"]

    if checkup_ids_array.ndim != 1:
        raise RuntimeError(
            f"checkup_ids must have shape [N]; got {checkup_ids_array.shape}."
        )
    checkup_count = checkup_ids_array.shape[0]
    if checkup_count == 0:
        raise RuntimeError("checkup_ids must contain at least one ID.")
    if patient_ids_array.shape != (checkup_count,):
        raise RuntimeError(
            f"patient_ids must have shape [{checkup_count}]; got {patient_ids_array.shape}."
        )
    if tooth_names_array.shape != (len(EXPECTED_TOOTH_NAMES),):
        raise RuntimeError(
            f"tooth_names must have shape [{len(EXPECTED_TOOTH_NAMES)}]; "
            f"got {tooth_names_array.shape}."
        )
    expected_embedding_prefix = (checkup_count, len(EXPECTED_TOOTH_NAMES))
    if (
        embeddings.ndim != 3
        or embeddings.shape[:2] != expected_embedding_prefix
        or embeddings.shape[2] == 0
    ):
        raise RuntimeError(
            f"embeddings must have shape [{checkup_count}, {len(EXPECTED_TOOTH_NAMES)}, D] "
            f"with D > 0; got {embeddings.shape}."
        )
    if not np.issubdtype(embeddings.dtype, np.floating):
        raise RuntimeError(f"embeddings must have a floating dtype; got {embeddings.dtype}.")
    if not np.all(np.isfinite(embeddings)):
        raise RuntimeError("embeddings must contain only finite values.")
    expected_present_shape = (checkup_count, len(EXPECTED_TOOTH_NAMES))
    if present.shape != expected_present_shape or present.dtype != np.bool_:
        raise RuntimeError(
            f"present must have shape {expected_present_shape} and bool dtype; "
            f"got {present.shape}, {present.dtype}."
        )

    checkup_ids = parse_string_array(checkup_ids_array, "checkup_ids")
    patient_ids = parse_string_array(patient_ids_array, "patient_ids")
    tooth_names = parse_string_array(tooth_names_array, "tooth_names")
    photo_fingerprints = parse_photo_fingerprints(photo_manifest_json, checkup_ids)
    if tooth_names != EXPECTED_TOOTH_NAMES:
        raise RuntimeError(
            "tooth_names has an unexpected order; "
            f"expected={EXPECTED_TOOTH_NAMES}, actual={tooth_names}"
        )

    index_by_checkup_id: dict[str, int] = {}
    for index, checkup_id in enumerate(checkup_ids):
        if checkup_id in index_by_checkup_id:
            raise RuntimeError(
                f"duplicate checkup_ids value at index {index}; "
                f"first seen at index {index_by_checkup_id[checkup_id]}: {checkup_id!r}"
            )
        index_by_checkup_id[checkup_id] = index

    return FeatureStore(
        patient_ids=patient_ids,
        embeddings=embeddings,
        present=present,
        photo_fingerprints=photo_fingerprints,
        index_by_checkup_id=index_by_checkup_id,
    )


def verify_feature_photo_manifests(
    pairs: list[PairRecord],
    features: FeatureStore,
    images_root: Path,
) -> dict[str, frozenset[str]]:
    if not images_root.is_dir():
        raise RuntimeError(f"COde images root was not found: {images_root}")

    references_by_checkup: dict[str, tuple[str, ...]] = {}
    for pair in pairs:
        for checkup_id, references in (
            (pair.template_id, pair.template_photographs),
            (pair.query_id, pair.query_photographs),
        ):
            if checkup_id in references_by_checkup:
                if references_by_checkup[checkup_id] != references:
                    raise RuntimeError(
                        f"inconsistent photograph references for checkup {checkup_id!r}."
                    )
            else:
                references_by_checkup[checkup_id] = references

    hash_by_path: dict[Path, str] = {}
    hashes_by_checkup: dict[str, frozenset[str]] = {}
    for checkup_id, expected_references in references_by_checkup.items():
        if checkup_id not in features.index_by_checkup_id:
            continue
        feature_index = features.index_by_checkup_id[checkup_id]
        fingerprints = features.photo_fingerprints[feature_index]
        stored_references = tuple(item.reference for item in fingerprints)
        if stored_references != expected_references:
            raise RuntimeError(
                f"feature photograph manifest mismatch for checkup {checkup_id!r}: "
                f"expected={expected_references}, actual={stored_references}"
            )

        for fingerprint in fingerprints:
            path = resolve_photo_reference(images_root, fingerprint.reference)
            if path not in hash_by_path:
                hash_by_path[path] = sha256_file(path)
            current_hash = hash_by_path[path]
            if current_hash != fingerprint.sha256:
                raise RuntimeError(
                    "photograph changed since feature extraction: "
                    f"checkup={checkup_id!r}, reference={fingerprint.reference!r}, "
                    f"expected={fingerprint.sha256}, actual={current_hash}"
                )
        hashes_by_checkup[checkup_id] = frozenset(
            fingerprint.sha256 for fingerprint in fingerprints
        )
    return hashes_by_checkup


def validate_feature_patient(
    features: FeatureStore,
    feature_index: int,
    expected_patient_id: str,
    checkup_id: str,
    pair: PairRecord,
) -> None:
    actual_patient_id = features.patient_ids[feature_index]
    if actual_patient_id != expected_patient_id:
        raise RuntimeError(
            f"feature patient ID mismatch for pair {pair.pair_id!r} at CSV row "
            f"{pair.source_row_number}: checkup_id={checkup_id!r}, "
            f"expected={expected_patient_id!r}, actual={actual_patient_id!r}"
        )


def finite_score(value: object, name: str, pair_id: str) -> float:
    if isinstance(value, (bool, np.bool_)) or not isinstance(value, Real):
        raise RuntimeError(f"{name} for pair {pair_id!r} must be a real number.")
    score = float(value)
    if not math.isfinite(score):
        raise RuntimeError(f"{name} for pair {pair_id!r} must be finite.")
    return score


def validate_matching_result(
    result: MatchingResultLike,
    expected_common_teeth: tuple[str, ...],
    pair_id: str,
) -> tuple[float, dict[str, float]]:
    if isinstance(result.common_teeth, tuple):
        common_teeth_matches = result.common_teeth == expected_common_teeth
    elif isinstance(result.common_teeth, (int, np.integer)) and not isinstance(
        result.common_teeth,
        (bool, np.bool_),
    ):
        common_teeth_matches = int(result.common_teeth) == len(expected_common_teeth)
    else:
        raise RuntimeError(
            f"common_teeth for pair {pair_id!r} must be an integer or tuple."
        )
    if not common_teeth_matches:
        raise RuntimeError(
            f"common_teeth mismatch for pair {pair_id!r}: "
            f"expected={expected_common_teeth}, actual={result.common_teeth}"
        )
    if not isinstance(result.per_tooth_scores, Mapping):
        raise RuntimeError(f"per_tooth_scores for pair {pair_id!r} must be a mapping.")
    if tuple(result.per_tooth_scores) != expected_common_teeth:
        raise RuntimeError(
            f"per_tooth_scores keys mismatch for pair {pair_id!r}: "
            f"expected={expected_common_teeth}, actual={tuple(result.per_tooth_scores)}"
        )

    per_tooth_scores = {
        tooth_name: finite_score(
            result.per_tooth_scores[tooth_name],
            f"per_tooth_scores[{tooth_name!r}]",
            pair_id,
        )
        for tooth_name in expected_common_teeth
    }
    return finite_score(result.fused_score, "fused_score", pair_id), per_tooth_scores


def missing_feature_reason(template_found: bool, query_found: bool) -> str:
    if not template_found and not query_found:
        return "missing_template_and_query_features"
    if not template_found:
        return "missing_template_feature"
    if not query_found:
        return "missing_query_feature"
    raise RuntimeError("missing_feature_reason called without a missing feature.")


def score_selected_pairs(
    pairs: list[PairRecord],
    features: FeatureStore,
    content_hashes: dict[str, frozenset[str]],
    min_common_teeth: int,
) -> tuple[list[ScoredPair], list[SkippedPair]]:
    scored: list[ScoredPair] = []
    skipped: list[SkippedPair] = []
    for pair in pairs:
        template_found = pair.template_id in features.index_by_checkup_id
        query_found = pair.query_id in features.index_by_checkup_id

        template_index: int | None = None
        query_index: int | None = None
        if template_found:
            template_index = features.index_by_checkup_id[pair.template_id]
            validate_feature_patient(
                features,
                template_index,
                pair.template_patient_id,
                pair.template_id,
                pair,
            )
        if query_found:
            query_index = features.index_by_checkup_id[pair.query_id]
            validate_feature_patient(
                features,
                query_index,
                pair.query_patient_id,
                pair.query_id,
                pair,
            )
        if template_index is None or query_index is None:
            skipped.append(
                SkippedPair(
                    pair=pair,
                    common_teeth=None,
                    reason=missing_feature_reason(template_found, query_found),
                )
            )
            continue

        shared_content = content_hashes[pair.template_id] & content_hashes[pair.query_id]
        if shared_content:
            skipped.append(
                SkippedPair(
                    pair=pair,
                    common_teeth=None,
                    reason="shared_photo_content",
                )
            )
            continue

        common_mask = features.present[template_index] & features.present[query_index]
        common_indices = np.flatnonzero(common_mask)
        common_teeth = tuple(EXPECTED_TOOTH_NAMES[index] for index in common_indices)
        if len(common_teeth) < min_common_teeth:
            skipped.append(
                SkippedPair(
                    pair=pair,
                    common_teeth=len(common_teeth),
                    reason="insufficient_common_teeth",
                )
            )
            continue

        result = score_pair(
            template_embeddings=features.embeddings[template_index],
            query_embeddings=features.embeddings[query_index],
            template_present=features.present[template_index],
            query_present=features.present[query_index],
            min_common_teeth=min_common_teeth,
        )
        fused_score, per_tooth_scores = validate_matching_result(
            result,
            common_teeth,
            pair.pair_id,
        )
        scored.append(
            ScoredPair(
                pair=pair,
                fused_score=fused_score,
                per_tooth_scores=per_tooth_scores,
                common_teeth=len(common_teeth),
            )
        )
    return scored, skipped


def write_scores_csv(path: Path, scored: list[ScoredPair]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=SCORE_COLUMNS)
        writer.writeheader()
        for record in scored:
            pair = record.pair
            writer.writerow(
                {
                    "query_id": pair.query_id,
                    "template_id": pair.template_id,
                    "query_subject_id": pair.query_patient_id,
                    "template_subject_id": pair.template_patient_id,
                    "query_session_id": pair.query_checkup_id,
                    "template_session_id": pair.template_checkup_id,
                    "is_genuine": int(pair.is_genuine),
                    "fused_score": f"{record.fused_score:.12g}",
                    "pair_id": pair.pair_id,
                    "split": pair.split,
                    "common_teeth": record.common_teeth,
                    "per_tooth_scores": json.dumps(
                        record.per_tooth_scores,
                        ensure_ascii=False,
                        separators=(",", ":"),
                        allow_nan=False,
                    ),
                }
            )


def write_skipped_csv(path: Path, skipped: list[SkippedPair]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=SKIPPED_COLUMNS)
        writer.writeheader()
        for record in skipped:
            pair = record.pair
            writer.writerow(
                {
                    "split": pair.split,
                    "pair_id": pair.pair_id,
                    "is_genuine": int(pair.is_genuine),
                    "template_id": pair.template_id,
                    "query_id": pair.query_id,
                    "template_patient_id": pair.template_patient_id,
                    "query_patient_id": pair.query_patient_id,
                    "template_checkup_id": pair.template_checkup_id,
                    "query_checkup_id": pair.query_checkup_id,
                    "template_photographs": "|".join(pair.template_photographs),
                    "query_photographs": "|".join(pair.query_photographs),
                    "common_teeth": "" if record.common_teeth is None else record.common_teeth,
                    "reason": record.reason,
                }
            )


def write_outputs_atomic(
    output_dir: Path,
    scored: list[ScoredPair],
    skipped: list[SkippedPair],
    summary: dict[str, object],
) -> None:
    generation_dir = create_generation_directory(output_dir)
    try:
        write_scores_csv(generation_dir / "scores.csv", scored)
        write_skipped_csv(generation_dir / "skipped_pairs.csv", skipped)
        (generation_dir / "summary.json").write_text(
            json.dumps(summary, indent=2, ensure_ascii=False, allow_nan=False) + "\n",
            encoding="utf-8",
        )
        publish_generation(generation_dir, output_dir)
    finally:
        discard_generation(generation_dir)


def run(args: argparse.Namespace) -> dict[str, object]:
    validate_args(args)
    require_file(args.pairs_csv, "pair CSV")
    require_file(args.features_npz, "feature NPZ")
    pairs = load_selected_pairs(args.pairs_csv, args.split, args.max_pairs)
    features = build_feature_store(args.features_npz)
    content_hashes = verify_feature_photo_manifests(pairs, features, args.images_root)
    scored, skipped = score_selected_pairs(
        pairs,
        features,
        content_hashes,
        args.min_common_teeth,
    )

    genuine_pairs = sum(record.pair.is_genuine for record in scored)
    impostor_pairs = len(scored) - genuine_pairs
    if genuine_pairs == 0:
        raise RuntimeError("no genuine pairs were scored.")
    if impostor_pairs == 0:
        raise RuntimeError("no impostor pairs were scored.")

    summary: dict[str, object] = {
        "pairs_csv_name": args.pairs_csv.name,
        "features_npz_name": args.features_npz.name,
        "split": args.split,
        "max_pairs": args.max_pairs,
        "min_common_teeth": args.min_common_teeth,
        "selected_pairs": len(pairs),
        "scored_pairs": len(scored),
        "skipped_pairs": len(skipped),
        "genuine_pairs": genuine_pairs,
        "impostor_pairs": impostor_pairs,
        "content_leakage_check": "extraction_sha256_verified_against_current_files",
        "skipped_by_reason": {
            reason: sum(record.reason == reason for record in skipped)
            for reason in sorted({record.reason for record in skipped})
        },
        "skipped_by_reason_and_label": {
            reason: {
                "genuine": sum(record.reason == reason and record.pair.is_genuine for record in skipped),
                "impostor": sum(record.reason == reason and not record.pair.is_genuine for record in skipped),
            }
            for reason in sorted({record.reason for record in skipped})
        },
    }
    write_outputs_atomic(args.output_dir, scored, skipped, summary)
    return summary


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    summary = run(args)
    scores_csv = args.output_dir / "scores.csv"
    skipped_csv = args.output_dir / "skipped_pairs.csv"
    summary_json = args.output_dir / "summary.json"
    print(f"scores: {scores_csv}")
    print(f"skipped: {skipped_csv}")
    print(f"summary: {summary_json}")
    print(
        f"scored_pairs={summary['scored_pairs']} skipped_pairs={summary['skipped_pairs']} "
        f"genuine_pairs={summary['genuine_pairs']} impostor_pairs={summary['impostor_pairs']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
